plugins {
    id 'mjjb.java-conventions'
    id 'mjjb.quality-conventions'
    id 'mjjb.coverage-conventions'
    id 'mjjb.native-conventions'
}

description = 'Basic generated-record JSON Schema binding example.'

sourceSets {
    main {
        java {
            srcDir 'generated-src/main/java'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone.excludedPaths.set('.*/generated-src/.*')
}

dependencies {
    implementation project(':modules:runtime-core')
    implementation project(':modules:parser-core')
}
