plugins {
    id 'mjjb.java-conventions'
    id 'mjjb.quality-conventions'
    id 'mjjb.coverage-conventions'
    id 'mjjb.publishing-conventions'
}

description = 'Test helpers for generated JSON bindings.'

publishing {
    publications {
        named('mavenJava', MavenPublication) {
            artifactId = 'mjjb-testing-support'
        }
    }
}

dependencies {
    api project(':modules:runtime-core')
}
